name: send testing data to api

on: [push]

jobs:

  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Bivas-Biswas/learn-gihub-actions@main
        with:
          user_id: ${{ secrets.DEVSNEST_USER_ID }}
          tha_no: ${{ secrets.DEVSNEST_THA_NO }}
