name: send testing data to api

on: [push]

jobs:

  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          user_id: ${{ secrets.DEVSNEST_USER_ID }}
          tha_no: ${{ secrets.DEVSNEST_THA_NO }}
        
      - run: |
          echo ${{ secrets.DEVSNEST_THA_NO }} | sed "s/./& /g"
